model: 'vgg16'
rpn_pooling_mode: 'align'

cuda: True
multi_gpu: False
cudnn_benchmark: False
cudnn_deterministic: False
num_workers: 4

# 数据集
#dataset_name: ['voc_2007', 'voc_2012']
#dataset_type: ['voc', 'voc']
#dataset_path: ['/dataset/pascal_voc/VOC2007', '/dataset/pascal_voc/VOC2012']
#image_set: ['trainval', 'trainval']
#use_difficult: [True, True]
dataset_name: ['voc_2007']
dataset_type: ['voc']
dataset_path: ['/dataset/pascal_voc/VOC2007']
image_set: ['trainval']
use_difficult: [True]

num_classes: 21
keep_all_gt_boxes: True

# 日志, 缓存
log_folder: './output/logs'
cache_path: './output/cache'

train:
#  resume: ''
  base_net: './output/faster_rcnn_base_vgg16_caffe_no_bn.pth'
  save_folder: './output/model'
  save_interval: 5000

  # 训练参数
  batch_size: 1
  lr: 0.001
  lr_steps: [50000, ]
  max_iter: 70000
  double_bias: True
  bias_decay: False
  gradient_clipping: True
  clip_norm: 10.

  # Vgg16 参数
  model_init: 'normal'
  truncated: False
  freeze_to: 'conv2_2'

  # Faster R-CNN 参数
  shortest_side: 600
  rpn_batch_size: 256
  rois_per_image: 256
  bg_threshold: (0.0, 0.5)
